// Authenticate
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SET_TOKEN = 'SET_TOKEN'
export const CLEAR_TOKEN = 'CLEAR_TOKEN'
export const REMEMBER_ME = 'REMEMBER_ME'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const GET_ME_REQUEST = 'GET_ME_REQUEST'
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS'
export const GET_ME_FAILURE = 'GET_ME_FAILURE'

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'

export const CHECK_TOKEN_REQUEST = 'CHECK_TOKEN_REQUEST'
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS'
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const APPROVE_USER_REQUEST = 'APPROVE_USER_REQUEST'
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS'
export const APPROVE_USER_FAILURE = 'APPROVE_USER_FAILURE'

export const GET_DEPARTMENT_REQUEST = 'GET_DEPARTMENT_REQUEST'
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPATMENT_SUCCESS'
export const GET_DEPARTMENT_FAILURE = 'GET_DEPARTMENT_FAILURE'

export const UPLOAD_USER_REQUEST = 'UPLOAD_USER_REQUEST'
export const UPLOAD_USER_PROGRESS = 'UPLOAD_USER_PROGRESS'
export const UPLOAD_USER_SUCCESS = 'UPLOAD_USER_SUCCESS'
export const UPLOAD_USER_FAILURE = 'UPLOAD_USER_FAILURE'

export const CHANGE_INDEX = 'CHANGE_INDEX'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const PROJECT_FILTERS = 'PROJECT_FILTERS'
export const USER_FILTERS = 'USER_FILTERS'
export const USER_FILTERS_RESET = 'USER_FILTERS_RESET'
export const USER_FILTER_MANAGE = 'USER_FILTER_MANAGE'
